### ISSUE TITLE
no luck with the example code

### ISSUE THREAD

**Issue by babsonmatt** [brigand/smart-mixin#4]
Gave the example code a run, but the result is `undefined` :(

**Comment by brigand** [comment]
Thanks!  Fixed in 1.0.2.  I'm still working on the tests for the actual mixin function – this will be done soon.  The bug was a missing return, which is kinda sad.

I added the example from the readme to an examples directory.  (`npm install && ./examples/readme/build.sh`).

**Comment by brigand** [comment]
@babsonmatt I've added more tests, it's not 100% but it's close.  Let me know if you have any further problems.
