### ISSUE TITLE
REDUCE_LEFT, REDUCE_RIGHT typo 

### ISSUE THREAD

**Issue by korzio** [brigand/smart-mixin#6]
Using mixin REDUCE_LEFT, REDUCE_RIGHT setting brings to an error
Uncaught ReferenceError: x is not defined

mixins.REDUCE_LEFT.left @ index.js?1de4:163 
mixins.REDUCE_LEFT @ index.js?1de4:166
module.exports.Object.keys.forEach.wrapIfFunction @ index.js?1de4:55

**Comment by brigand** [comment]
Fixed in brigand/smart-mixin/pull/7
